<?php

namespace AppBundle\Repository;

/**
 * benefitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class benefitRepository extends \Doctrine\ORM\EntityRepository
{
}
