<?php

namespace AppBundle\Repository;

/**
 * TimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimelineRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDate()
    {
        $query = $this->_em->createQuery('SELECT t FROM AppBundle:Timeline t ORDER BY t.dateStart DESC');
        $result = $query->getResult();
        return $result;
    }
}
