<?php

namespace AppBundle\Repository;

/**
 * VpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VpRepository extends \Doctrine\ORM\EntityRepository
{
}
